name: Atualização IPTV

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 10 minutos (ajuste conforme necessário)

jobs:
  update_iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Especifique a versão do Python que você está usando

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Se você tiver um arquivo requirements.txt com as dependências do seu script

      - name: Executar script Python
        run: python maclopes2/meuscanais/updateiptv.py  # Substitua pelo caminho para o seu script Python

      - name: Commit e push de volta ao repositório
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add maclopes2/meuscanais/teste  # Substitua pelo caminho para o arquivo que você está atualizando
          git commit -m "Atualização automática de IPTV"
          git push


