# .github/workflows/update_iptv.yml

name: Atualização Automática de IPTV

on:
  schedule:
    - cron: '*/5 * * * *'  # Executa a cada 5 minutos (ajuste conforme necessário)

jobs:
  update_iptv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifique a versão do Python necessária
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests
      
      - name: Executar script Python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python script.py
